### ISSUE TITLE
We had an issue deploying…

### ISSUE THREAD

**Issue by aarongustafson** [molocLab/10k#1]
Can you add a `web.config` file pointing to `dist` as the root folder? We don’t have a PHP web.config template (most people put index.php in the root), but you can check out the sample ones for [Node](https://a-k-apart.com/webconfigs/web.config.node.txt) and [Python](https://a-k-apart.com/webconfigs/web.config.python.txt) if you want a starter template.

**Comment by molocLab** [comment]
I Can move "dist" content into the root so that index.php is the root
folder and maintain "source" folder just as documentation.

Is It ok for you?

Il 15 set 2016 9:19 PM, "Aaron Gustafson" <notifications@github.com> ha
scritto:

**Comment by aarongustafson** [comment]
That should work, yes.

**Comment by molocLab** [comment]
Done! :)
